// <auto-generated />
using EfInheritance.Repository.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfInheritance.Migrations
{
    [DbContext(typeof(InheritanceContext))]
    [Migration("20240119163734_Table per Hierachy")]
    partial class TableperHierachy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EfInheritance.Repository.DbModels.Vechicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vechicles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Vechicle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EfInheritance.Repository.DbModels.Bike", b =>
                {
                    b.HasBaseType("EfInheritance.Repository.DbModels.Vechicle");

                    b.Property<string>("BikeSize")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Bike");
                });

            modelBuilder.Entity("EfInheritance.Repository.DbModels.Car", b =>
                {
                    b.HasBaseType("EfInheritance.Repository.DbModels.Vechicle");

                    b.Property<string>("CarSize")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
